#Container name automatically the name of whatever the parent folder is
name: Footlocker
services:
  kickbot:
    build:
      context: /home/tyler/Documents/ShoeBot_Pi
      dockerfile: Dockerfile
    image: kickbot
    container_name: Footlocker
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - /home/tyler/Documents/ShoeBot_Pi/sros_ws:/root/colcon_ws
    devices:
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/spidev0.1:/dev/spidev0.1
      - /dev/gpiomem:/dev/gpiomem
      - /dev/gpiochip0:/dev/gpiochip0
    command: >
      bash -c "source /ros_entrypoint.sh &&
               cd /root/colcon_ws &&
               colcon build --executor sequential &&
               source install/setup.bash &&
               cd launch &&
               bash kickstart_motor_test.sh"